### ISSUE TITLE
Implicit dependency on 'Hub', local directory structure

### ISSUE THREAD

**Issue by jasonhemann** [mfelleisen/Fish#1]
Both [protocol](https://github.com/mfelleisen/Fish/blob/a2b73f6d5312c42c4700c8ecd7a073fe18bd83e4/scribblings/protocol.scrbl#L15) and [remote](https://github.com/mfelleisen/Fish/blob/a2b73f6d5312c42c4700c8ecd7a073fe18bd83e4/scribblings/remote.scrbl#L24) implicitly rely on a local directory structure convention. Does this want to be a configuration variable?

**Comment by jasonhemann** [comment]
I meant specifically that it builds a `$HOME/Hub/Fish/.../` path. If the user installs in a different directory, then setup and `raco doc` will fail.

**Comment by mfelleisen** [comment]
OH, that should not be the case.

**Comment by mfelleisen** [comment]
Ah, it’s the doc files that depend on the `Hub` path. I think I can fix this .. hopefully soon-ish

**Comment by jasonhemann** [comment]
Should I be following the branch `trace` instead of `master`?

**Comment by mfelleisen** [comment]
No, the push should have been to both.
